server:
  port:
    8090

spring:
  application:
    name:
      GraphQLPrimer

logging:
  level:
    com:
      suraj:
        api:
          INFO
  file:
    clean-history-on-start:
      true
    name:
      logs/${spring.application.name}.log  


graphql:
  servlet:
    mapping: /graphql
    enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true
